name: Build and Deploy
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        persist-credentials: false
    - name: Install modules
      run: |
        yarn install   
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3 
      with:
        branch: gh-pages
        #folder: build
        ssh-key: ${{ secrets.git-key }}
